# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SeaCharter
                                 A QGIS plugin
 Chart courses at sea
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-31
        copyright            : (C) 2023 by Itai Levin
        email                : Levin Itai
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SeaCharter class from file SeaCharter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SeaCharter import SeaCharter
    return SeaCharter(iface)
